### ISSUE TITLE
Errors compiling

### ISSUE THREAD

**Issue by ntassani** [milohr/babe-music-player#1]
Hi Camilo! I cant compile the program.
I do your recommmended steps but im getting:

nicolai@nicolai-SVF14213CLB:~/Descargas/babe-music-player-master$ valac --pkg gstreamer-1.0 --pkg gtk+-3.0 --pkg taglib_c --pkg gee-1.0 --pkg libxml-2.0 --pkg libsoup-2.4 --pkg libnotify babe.vala stream.vala lastfm.vala widgets.vala LyricFetcher.vala
widgets.vala:24.7-24.14: error: The namespace name `BabeList' could not be found
using BabeList;
      ^^^^^^^^
widgets.vala:25.7-25.18: error: The namespace name`BabePlayList' could not be found
using BabePlayList;
      ^^^^^^^^^^^^
widgets.vala:34.9-34.13: error: The type name `BList' could not be found
    public BList main_list;
           ^^^^^
widgets.vala:35.9-35.13: error: The type name`BList' could not be found
    public BList queue_list;
           ^^^^^
widgets.vala:36.9-36.13: error: The type name `BList' could not be found
    public BList babes_list;
           ^^^^^
widgets.vala:37.9-37.13: error: The type name`BList' could not be found
    public BList playlist;
           ^^^^^
widgets.vala:38.9-38.17: error: The type name `BPlayList' could not be found
    public BPlayList playlist_list;
           ^^^^^^^^^
widgets.vala:906.15-906.19: error: The type name`BList' could not be found
        var list = (BList) widget;
                    ^^^^^
widgets.vala:985.9-985.13: error: The type name `BList' could not be found
    public BList get_BList_object(Gtk.TreeModel model)
           ^^^^^
Compilation failed: 9 error(s), 0 warning(s)

Any help?
Thanks! The player looks amazing :)

**Comment by milohr** [comment]
Hello. It was missing the playlist.vala file. I've updated the read me file with the right compiling lines. You can now try again and let me know. There are still a lot of bugs and missing features.
