### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by momoe** [milohr/babe-music-player#4]
Hi hiii, I was pulling your git to test out on Arch Linux 64-bit GNOME v3.24.1  and it failed to compile. Here is the build log to provide the information. 

https://pastebin.com/uYyY5wSw

**Comment by milohr** [comment]
a fix is now on master :) could you test it? and if it works please close this issue? thanks.

**Comment by milohr** [comment]
btw you're reporting this issue in the wrong repository.
https://github.com/milohr/babe-qt
